version: '3.8'

services:
  app:
    build:
      context: .
    container_name: laravel-app
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  node:
    image: node:18
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: >
      sh -c "npm install && npm run dev"
    depends_on:
      - app

volumes:
  dbdata:
